### ISSUE TITLE
ToC 다른 항목이 active되는 현상

### ISSUE THREAD

**Issue by pok8** [velopert/velog#10]
ToC 에서 항목 클릭 시 이동은 잘 되는데 다른 항목이 active되는 현상이 있습니다.
![honeycam 2018-09-04 17-26-52](https://user-images.githubusercontent.com/35554208/45019766-1d550a80-b068-11e8-98c2-91f9b00b87c4.gif)

**Comment by velopert** [comment]
아마도 고쳐졌을듯..?! 안고쳐졌으면 다시 open 할게요!
