### ISSUE TITLE
shortcut icon 

### ISSUE THREAD

**Issue by defdict** [velopert/velog#3]
![image](https://user-images.githubusercontent.com/25701359/44296850-43a54700-a301-11e8-930f-608870d404a9.png)

일부러 초기 상태로 유지하시는건지는 모르겠지만 velog 공식 로고로 바꾸는건 어떨까요?

**Comment by velopert** [comment]
이 부분은 조만간 아는 디자이너분께 요청하게 될 것 같습니다 :)
공개하기전에는 임시로라도 만들어야겠네요 ㅋㅋㅋ
