### ISSUE TITLE
포스트 에디터 HTML 구문강조 오류

### ISSUE THREAD

**Issue by Oslint** [velopert/velog#38]
![image](https://user-images.githubusercontent.com/37634063/46253169-8b49f180-c4af-11e8-913c-04be3e2d0951.png)
![image](https://user-images.githubusercontent.com/37634063/46253176-ac124700-c4af-11e8-9181-846c442d2049.png)
위에서 보이듯이 HTML 태그의 속성의 변수 안에 공백이 들어가면 첫번째 태그의 강조가 사라집니다.
탭이나 한글채움 문자는 그렇지 않고 오로지 스페이스바 공백(U+0020)만 이런 현상이 발생합니다.

**Comment by velopert** [comment]
아직까지는 HTML 을 마크다운에서 허용하고있지는 않기 때문에 닫아두겠습니다~

**Comment by velopert** [comment]
(정확히는 velog 의 마크다운에서..)
