### ISSUE TITLE
네이버 이메일로 회원가입 후 로그인 할 수 없음.

### ISSUE THREAD

**Issue by sunsnow88** [velopert/velog#57]
네이버 이메일로 회원가입을 했습니다.
다시 처음 페이지에서 로그인 하려고 하니 구글과 페이스북 로그인 버튼만 있고 
이메일이나 아이디로 로그인 하는 부분이 없습니다.

**Comment by velopert** [comment]
![image](https://user-images.githubusercontent.com/17202261/48469020-ea31b300-e830-11e8-86e6-c77f8fc9bd80.png)
상단에에 보여지는, "이메일을 입력해주세요" 부분이 안나타나는지요?

**Comment by 9oose** [comment]
벨로퍼트님께 보내시는건지?? 메일이 잘못 온거같네여 ㅎㅎ

2018년 11월 14일 (수) 오후 5:13, sunsnow88 <notifications@github.com>님이 작성:

**Comment by velopert** [comment]
ㅋㅋㅋ github 쪽에 watch 누르셔서 이슈 알림이 간것 같아요 :) 근데
깃헙이슈를 이메일 회신으로도 할 수 있는건 방금 알았네요 :0

**Comment by 9oose** [comment]
안 그렇군요! ㅎㅎ 팬입니다 하핫 그럼 이만 :)

2018년 11월 14일 (수) 오후 5:18, Minjun Kim <notifications@github.com>님이 작성:

**Comment by sunsnow88** [comment]
보여주신 이미지처럼 회원가입을 하고 이메일로 온 링크나 계속하기를 눌러야만 로그인 된 상태로 되나보네요. 
pc로 요청을 하구 핸드폰으로 이메일 확인을 해서 그런거 같네요. ㅎ

**Comment by velopert** [comment]
이것도 언젠간 더 개선하는걸로...
