### ISSUE TITLE
내 벨로그 오류

### ISSUE THREAD

**Issue by 9oose** [velopert/velog#59]
내 벨로그 부분에서 다음과 같이 썸네일 오류가 납니다 벨로퍼트님

![default](https://user-images.githubusercontent.com/16398603/48534742-60472000-e8ec-11e8-9746-c5cf16c1ceb6.PNG)

cors문제인거 같네용

**Comment by velopert** [comment]
음... 500이 떴던것같은데
저번에 해결을 한것같기도한데
재현이 안돼서 일단은 Close :)
