### ISSUE TITLE
글작성시 썸네일에 한글 파일명이 들어가면 글작성에 실패함.

### ISSUE THREAD

**Issue by junwoochoi** [velopert/velog#63]
400 에러와 함께 작성 실패 토스트가 띄어집니다.

![default](https://user-images.githubusercontent.com/26688947/49925185-849e1880-fefb-11e8-8b82-0421b043fca0.PNG)
![1](https://user-images.githubusercontent.com/26688947/49925186-849e1880-fefb-11e8-9273-cb7aaab585fa.PNG)

**Comment by velopert** [comment]
고친것..같긴한데 제 컴퓨터에서는 재현이 안돼서 확인을 못해봤습니다.
한번 재시도 하시고 문제발생하면 다시 이슈 열어주세요

**Comment by junwoochoi** [comment]
고쳐진것 같습니다. 감사합니다!
