### ISSUE TITLE
code highlighting (java) 

### ISSUE THREAD

**Issue by umanking** [velopert/velog#75]
안녕하세요 벨로퍼트님 ^^ !!
code block에서 자바 코드가 예제상에서는 하이라이팅이 잘 되는데, 
작성해서 올리거나, preview 버전에서는 잘 나오지 않아서
혹시 이슈에 대해서 문의드립니다 ~ 
<img width="1552" alt="2019-02-05 12 30 42" src="https://user-images.githubusercontent.com/28615416/52251726-f9149700-2941-11e9-832c-86f09894c0ae.png">

**Comment by junwoochoi** [comment]
![image](https://user-images.githubusercontent.com/26688947/52929968-e9597180-3389-11e9-93f1-d979d869133e.png)

저도 유독 자바만 하이라이팅이 안되네요ㅠ.ㅠ

**Comment by eungook** [comment]
에디터에서는 하이라이트가 잘 되는데요

![image](https://user-images.githubusercontent.com/11587634/70294353-85c00800-1826-11ea-9591-97ad8be60a92.png)
![image](https://user-images.githubusercontent.com/11587634/70294367-8c4e7f80-1826-11ea-8a3a-7e6d3e8464f7.png)
![image](https://user-images.githubusercontent.com/11587634/70294392-a4be9a00-1826-11ea-8ab6-aef55d7eb123.png)

미리보기, 실제 페이지에 가보면 자바 하이라이트가 안 되어 있어요~
