### ISSUE TITLE
mathJax 기능 제안합니다.

### ISSUE THREAD

**Issue by jwon0615** [velopert/velog#89]
$$\frac{1}{\pi}$$
식으로 사용 가능한 수식 입력 기능을 제안합니다!!

**Comment by velopert** [comment]
현재 velog v2 가 개발진행중인데, 추후 고려해보도록 하겠습니다~ 
v2  는 다른 레포에서 관리중인데 레퍼해놨어요~

**Comment by nck2** [comment]
저도 이 기능요청하려고 들어왔어요. 수식 기능 들어갔으면 좋겠습니다.!!
