### ISSUE TITLE
No more maintenance?

### ISSUE THREAD

**Issue by turastory** [velopert/velog#90]
정말 좋은 프로젝트이고.. 그런 만큼 개선 의지를 가지고 있는 분들이 많이 있는데, 이슈나 PR에 대한 팔로업이 없는 것 같아서 너무 아쉽습니다.

다른 프로젝트나 일로 인해서 바쁘시다면, 혹시 메인테이너같은 분을 두실 생각은 없는지 궁금합니다.

불편한 부분에 대한 수정을 직접 해보고 싶은데, 그다지 액티브한 프로젝트가 아닌 것 같아서 참여하기가 망설여지네요.

**Comment by velopert** [comment]
안녕하세요,
일단 기존 이슈나 풀리퀘스트를 요즘 처리하고 있지 못해서 죄송합니다.

그렇지만 개발이 중단된것은 아니고..

https://github.com/velopert/velog-client
https://github.com/velopert/velog-server

에서 리뉴얼이 진행되고 있으며

올해 말이나 내년 초에 릴리즈 될 것으로 예상합니다.

추가적으로, 기존 벨로그에서는 치명적인 이슈는 처리하려고 하고 있습니다.

감사합니다.

**Comment by turastory** [comment]
답변 감사합니다 :) 리뉴얼 기대하겠습니다.
